<?php
/**
 * GeocodingApi
 * PHP version 7.3
 *
 * @category Class
 * @package  GeoCodes
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * geo.codes
 *
 * The alpha version of the https://geo.codes API service. 10,000 free queries per month.
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GeoCodes\GeoCodes;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GeoCodes\ApiException;
use GeoCodes\Configuration;
use GeoCodes\HeaderSelector;
use GeoCodes\ObjectSerializer;

/**
 * GeocodingApi Class Doc Comment
 *
 * @category Class
 * @package  GeoCodes
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GeocodingApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1AddressGeocode
     *
     * @param  string $q The unstructured address to geocode. Expected to be roughly the format that is used by the USPS to deliver mail. (required)
     * @param  int $min_confidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don&#39;t recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match. (optional)
     *
     * @throws \GeoCodes\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \GeoCodes\Model\ModelutilGeocoding
     */
    public function v1AddressGeocode($q, $min_confidence = null)
    {
        list($response) = $this->v1AddressGeocodeWithHttpInfo($q, $min_confidence);
        return $response;
    }

    /**
     * Operation v1AddressGeocodeWithHttpInfo
     *
     * @param  string $q The unstructured address to geocode. Expected to be roughly the format that is used by the USPS to deliver mail. (required)
     * @param  int $min_confidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don&#39;t recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match. (optional)
     *
     * @throws \GeoCodes\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \GeoCodes\Model\ModelutilGeocoding, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AddressGeocodeWithHttpInfo($q, $min_confidence = null)
    {
        $request = $this->v1AddressGeocodeRequest($q, $min_confidence);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\GeoCodes\Model\ModelutilGeocoding' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\GeoCodes\Model\ModelutilGeocoding', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\GeoCodes\Model\ModelutilGeocoding';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoCodes\Model\ModelutilGeocoding',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1AddressGeocodeAsync
     *
     * @param  string $q The unstructured address to geocode. Expected to be roughly the format that is used by the USPS to deliver mail. (required)
     * @param  int $min_confidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don&#39;t recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AddressGeocodeAsync($q, $min_confidence = null)
    {
        return $this->v1AddressGeocodeAsyncWithHttpInfo($q, $min_confidence)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AddressGeocodeAsyncWithHttpInfo
     *
     * @param  string $q The unstructured address to geocode. Expected to be roughly the format that is used by the USPS to deliver mail. (required)
     * @param  int $min_confidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don&#39;t recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AddressGeocodeAsyncWithHttpInfo($q, $min_confidence = null)
    {
        $returnType = '\GeoCodes\Model\ModelutilGeocoding';
        $request = $this->v1AddressGeocodeRequest($q, $min_confidence);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AddressGeocode'
     *
     * @param  string $q The unstructured address to geocode. Expected to be roughly the format that is used by the USPS to deliver mail. (required)
     * @param  int $min_confidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don&#39;t recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AddressGeocodeRequest($q, $min_confidence = null)
    {
        // verify the required parameter 'q' is set
        if ($q === null || (is_array($q) && count($q) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $q when calling v1AddressGeocode'
            );
        }
        if ($min_confidence !== null && $min_confidence > 100) {
            throw new \InvalidArgumentException('invalid value for "$min_confidence" when calling GeocodingApi.v1AddressGeocode, must be smaller than or equal to 100.');
        }


        $resourcePath = '/v1/address/geocode';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($min_confidence !== null) {
            if('form' === 'form' && is_array($min_confidence)) {
                foreach($min_confidence as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['min_confidence'] = $min_confidence;
            }
        }
        // query params
        if ($q !== null) {
            if('form' === 'form' && is_array($q)) {
                foreach($q as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['q'] = $q;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AddressReverseZipCode
     *
     * @param  double $latitude The latitude of the query. (required)
     * @param  double $longitude The longitude of the query. (required)
     * @param  bool $strict If true, will only return a result if the given point is within a zip code tabulation area, and will not return the closest one. (optional)
     *
     * @throws \GeoCodes\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \GeoCodes\Model\ModelutilReverseZIPCode
     */
    public function v1AddressReverseZipCode($latitude, $longitude, $strict = null)
    {
        list($response) = $this->v1AddressReverseZipCodeWithHttpInfo($latitude, $longitude, $strict);
        return $response;
    }

    /**
     * Operation v1AddressReverseZipCodeWithHttpInfo
     *
     * @param  double $latitude The latitude of the query. (required)
     * @param  double $longitude The longitude of the query. (required)
     * @param  bool $strict If true, will only return a result if the given point is within a zip code tabulation area, and will not return the closest one. (optional)
     *
     * @throws \GeoCodes\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \GeoCodes\Model\ModelutilReverseZIPCode, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AddressReverseZipCodeWithHttpInfo($latitude, $longitude, $strict = null)
    {
        $request = $this->v1AddressReverseZipCodeRequest($latitude, $longitude, $strict);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\GeoCodes\Model\ModelutilReverseZIPCode' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\GeoCodes\Model\ModelutilReverseZIPCode', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\GeoCodes\Model\ModelutilReverseZIPCode';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoCodes\Model\ModelutilReverseZIPCode',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1AddressReverseZipCodeAsync
     *
     * @param  double $latitude The latitude of the query. (required)
     * @param  double $longitude The longitude of the query. (required)
     * @param  bool $strict If true, will only return a result if the given point is within a zip code tabulation area, and will not return the closest one. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AddressReverseZipCodeAsync($latitude, $longitude, $strict = null)
    {
        return $this->v1AddressReverseZipCodeAsyncWithHttpInfo($latitude, $longitude, $strict)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AddressReverseZipCodeAsyncWithHttpInfo
     *
     * @param  double $latitude The latitude of the query. (required)
     * @param  double $longitude The longitude of the query. (required)
     * @param  bool $strict If true, will only return a result if the given point is within a zip code tabulation area, and will not return the closest one. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AddressReverseZipCodeAsyncWithHttpInfo($latitude, $longitude, $strict = null)
    {
        $returnType = '\GeoCodes\Model\ModelutilReverseZIPCode';
        $request = $this->v1AddressReverseZipCodeRequest($latitude, $longitude, $strict);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AddressReverseZipCode'
     *
     * @param  double $latitude The latitude of the query. (required)
     * @param  double $longitude The longitude of the query. (required)
     * @param  bool $strict If true, will only return a result if the given point is within a zip code tabulation area, and will not return the closest one. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AddressReverseZipCodeRequest($latitude, $longitude, $strict = null)
    {
        // verify the required parameter 'latitude' is set
        if ($latitude === null || (is_array($latitude) && count($latitude) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $latitude when calling v1AddressReverseZipCode'
            );
        }
        if ($latitude > 90) {
            throw new \InvalidArgumentException('invalid value for "$latitude" when calling GeocodingApi.v1AddressReverseZipCode, must be smaller than or equal to 90.');
        }
        if ($latitude < -90) {
            throw new \InvalidArgumentException('invalid value for "$latitude" when calling GeocodingApi.v1AddressReverseZipCode, must be bigger than or equal to -90.');
        }

        // verify the required parameter 'longitude' is set
        if ($longitude === null || (is_array($longitude) && count($longitude) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $longitude when calling v1AddressReverseZipCode'
            );
        }
        if ($longitude > 180) {
            throw new \InvalidArgumentException('invalid value for "$longitude" when calling GeocodingApi.v1AddressReverseZipCode, must be smaller than or equal to 180.');
        }
        if ($longitude < -180) {
            throw new \InvalidArgumentException('invalid value for "$longitude" when calling GeocodingApi.v1AddressReverseZipCode, must be bigger than or equal to -180.');
        }


        $resourcePath = '/v1/address/reverse_zip_code';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($latitude !== null) {
            if('form' === 'form' && is_array($latitude)) {
                foreach($latitude as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['latitude'] = $latitude;
            }
        }
        // query params
        if ($longitude !== null) {
            if('form' === 'form' && is_array($longitude)) {
                foreach($longitude as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['longitude'] = $longitude;
            }
        }
        // query params
        if ($strict !== null) {
            if('form' === 'form' && is_array($strict)) {
                foreach($strict as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['strict'] = $strict;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AddressStructuredGeocode
     *
     * @param  string $street_address The street address line, including the number and street type. An example is &#39;101 Main St&#39;. (required)
     * @param  string $city The city. Not required, but it&#39;s highly recommended that you add either the city or postal_code fields. (optional)
     * @param  int $min_confidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don&#39;t recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match. (optional)
     * @param  string $postal_code The postal code, for example, a ZIP code. Not required, but if this is not present, we recommend adding the city and the state for best results. (optional)
     * @param  string $state The state with the address. Not required, but it&#39;s highly recommended that you add the postal_code if the state is not present. (optional)
     *
     * @throws \GeoCodes\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \GeoCodes\Model\ModelutilGeocoding
     */
    public function v1AddressStructuredGeocode($street_address, $city = null, $min_confidence = null, $postal_code = null, $state = null)
    {
        list($response) = $this->v1AddressStructuredGeocodeWithHttpInfo($street_address, $city, $min_confidence, $postal_code, $state);
        return $response;
    }

    /**
     * Operation v1AddressStructuredGeocodeWithHttpInfo
     *
     * @param  string $street_address The street address line, including the number and street type. An example is &#39;101 Main St&#39;. (required)
     * @param  string $city The city. Not required, but it&#39;s highly recommended that you add either the city or postal_code fields. (optional)
     * @param  int $min_confidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don&#39;t recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match. (optional)
     * @param  string $postal_code The postal code, for example, a ZIP code. Not required, but if this is not present, we recommend adding the city and the state for best results. (optional)
     * @param  string $state The state with the address. Not required, but it&#39;s highly recommended that you add the postal_code if the state is not present. (optional)
     *
     * @throws \GeoCodes\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \GeoCodes\Model\ModelutilGeocoding, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AddressStructuredGeocodeWithHttpInfo($street_address, $city = null, $min_confidence = null, $postal_code = null, $state = null)
    {
        $request = $this->v1AddressStructuredGeocodeRequest($street_address, $city, $min_confidence, $postal_code, $state);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\GeoCodes\Model\ModelutilGeocoding' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\GeoCodes\Model\ModelutilGeocoding', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\GeoCodes\Model\ModelutilGeocoding';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoCodes\Model\ModelutilGeocoding',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1AddressStructuredGeocodeAsync
     *
     * @param  string $street_address The street address line, including the number and street type. An example is &#39;101 Main St&#39;. (required)
     * @param  string $city The city. Not required, but it&#39;s highly recommended that you add either the city or postal_code fields. (optional)
     * @param  int $min_confidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don&#39;t recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match. (optional)
     * @param  string $postal_code The postal code, for example, a ZIP code. Not required, but if this is not present, we recommend adding the city and the state for best results. (optional)
     * @param  string $state The state with the address. Not required, but it&#39;s highly recommended that you add the postal_code if the state is not present. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AddressStructuredGeocodeAsync($street_address, $city = null, $min_confidence = null, $postal_code = null, $state = null)
    {
        return $this->v1AddressStructuredGeocodeAsyncWithHttpInfo($street_address, $city, $min_confidence, $postal_code, $state)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AddressStructuredGeocodeAsyncWithHttpInfo
     *
     * @param  string $street_address The street address line, including the number and street type. An example is &#39;101 Main St&#39;. (required)
     * @param  string $city The city. Not required, but it&#39;s highly recommended that you add either the city or postal_code fields. (optional)
     * @param  int $min_confidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don&#39;t recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match. (optional)
     * @param  string $postal_code The postal code, for example, a ZIP code. Not required, but if this is not present, we recommend adding the city and the state for best results. (optional)
     * @param  string $state The state with the address. Not required, but it&#39;s highly recommended that you add the postal_code if the state is not present. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AddressStructuredGeocodeAsyncWithHttpInfo($street_address, $city = null, $min_confidence = null, $postal_code = null, $state = null)
    {
        $returnType = '\GeoCodes\Model\ModelutilGeocoding';
        $request = $this->v1AddressStructuredGeocodeRequest($street_address, $city, $min_confidence, $postal_code, $state);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AddressStructuredGeocode'
     *
     * @param  string $street_address The street address line, including the number and street type. An example is &#39;101 Main St&#39;. (required)
     * @param  string $city The city. Not required, but it&#39;s highly recommended that you add either the city or postal_code fields. (optional)
     * @param  int $min_confidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don&#39;t recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match. (optional)
     * @param  string $postal_code The postal code, for example, a ZIP code. Not required, but if this is not present, we recommend adding the city and the state for best results. (optional)
     * @param  string $state The state with the address. Not required, but it&#39;s highly recommended that you add the postal_code if the state is not present. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AddressStructuredGeocodeRequest($street_address, $city = null, $min_confidence = null, $postal_code = null, $state = null)
    {
        // verify the required parameter 'street_address' is set
        if ($street_address === null || (is_array($street_address) && count($street_address) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $street_address when calling v1AddressStructuredGeocode'
            );
        }
        if ($min_confidence !== null && $min_confidence > 100) {
            throw new \InvalidArgumentException('invalid value for "$min_confidence" when calling GeocodingApi.v1AddressStructuredGeocode, must be smaller than or equal to 100.');
        }
        if ($min_confidence !== null && $min_confidence < 1) {
            throw new \InvalidArgumentException('invalid value for "$min_confidence" when calling GeocodingApi.v1AddressStructuredGeocode, must be bigger than or equal to 1.');
        }


        $resourcePath = '/v1/address/structured_geocode';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($city !== null) {
            if('form' === 'form' && is_array($city)) {
                foreach($city as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['city'] = $city;
            }
        }
        // query params
        if ($min_confidence !== null) {
            if('form' === 'form' && is_array($min_confidence)) {
                foreach($min_confidence as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['min_confidence'] = $min_confidence;
            }
        }
        // query params
        if ($postal_code !== null) {
            if('form' === 'form' && is_array($postal_code)) {
                foreach($postal_code as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['postal_code'] = $postal_code;
            }
        }
        // query params
        if ($state !== null) {
            if('form' === 'form' && is_array($state)) {
                foreach($state as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['state'] = $state;
            }
        }
        // query params
        if ($street_address !== null) {
            if('form' === 'form' && is_array($street_address)) {
                foreach($street_address as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['street_address'] = $street_address;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AddressZipCode
     *
     * @param  string $zip_code The ZIP Code of the query. Can be a ZIP Code or a ZIP+4 Code. If a +4 extension is passed, it will be ignored. (required)
     *
     * @throws \GeoCodes\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \GeoCodes\Model\ModelutilGCSCoordinate
     */
    public function v1AddressZipCode($zip_code)
    {
        list($response) = $this->v1AddressZipCodeWithHttpInfo($zip_code);
        return $response;
    }

    /**
     * Operation v1AddressZipCodeWithHttpInfo
     *
     * @param  string $zip_code The ZIP Code of the query. Can be a ZIP Code or a ZIP+4 Code. If a +4 extension is passed, it will be ignored. (required)
     *
     * @throws \GeoCodes\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \GeoCodes\Model\ModelutilGCSCoordinate, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AddressZipCodeWithHttpInfo($zip_code)
    {
        $request = $this->v1AddressZipCodeRequest($zip_code);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\GeoCodes\Model\ModelutilGCSCoordinate' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\GeoCodes\Model\ModelutilGCSCoordinate', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\GeoCodes\Model\ModelutilGCSCoordinate';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoCodes\Model\ModelutilGCSCoordinate',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1AddressZipCodeAsync
     *
     * @param  string $zip_code The ZIP Code of the query. Can be a ZIP Code or a ZIP+4 Code. If a +4 extension is passed, it will be ignored. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AddressZipCodeAsync($zip_code)
    {
        return $this->v1AddressZipCodeAsyncWithHttpInfo($zip_code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AddressZipCodeAsyncWithHttpInfo
     *
     * @param  string $zip_code The ZIP Code of the query. Can be a ZIP Code or a ZIP+4 Code. If a +4 extension is passed, it will be ignored. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AddressZipCodeAsyncWithHttpInfo($zip_code)
    {
        $returnType = '\GeoCodes\Model\ModelutilGCSCoordinate';
        $request = $this->v1AddressZipCodeRequest($zip_code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AddressZipCode'
     *
     * @param  string $zip_code The ZIP Code of the query. Can be a ZIP Code or a ZIP+4 Code. If a +4 extension is passed, it will be ignored. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AddressZipCodeRequest($zip_code)
    {
        // verify the required parameter 'zip_code' is set
        if ($zip_code === null || (is_array($zip_code) && count($zip_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $zip_code when calling v1AddressZipCode'
            );
        }

        $resourcePath = '/v1/address/zip_code';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($zip_code !== null) {
            if('form' === 'form' && is_array($zip_code)) {
                foreach($zip_code as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['zip_code'] = $zip_code;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
